version: '2'
services:

  blog-api:
    image: madoos/blog-api:ci
    tty: true
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - DEBUG=*
  blog-api-rotherb:
    image: madoos/blog-api:latest
    tty: true
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=production
      - DEBUG=*